apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-configuration
data:
  init.sh: |-
    #!/bin/bash
    gcloud auth activate-service-account 943631578651-compute@developer.gserviceaccount.com --key-file /etc/gke/service-account.json
    gcloud container clusters get-credentials zonar-production-cluster --zone us-east1-b --project sds-readiness
    helm init
    chmod +x /usr/bin/kubectl
    tail -f /dev/null