apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/etc/k8s-config/init.sh"]
#          - gcloud auth activate-service-account 943631578651-compute@developer.gserviceaccount.com --key-file /etc/gke/service-account.json
#          - gcloud container clusters get-credentials zonar-production-cluster --zone us-east1-b --project sds-readiness

        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
            -
              mountPath: /etc/jenkins-ssh-keys
              name: jenkins-ssh-keys
              readOnly: true
            -
              mountPath: /etc/gke
              name: jenkins-gke-keys
              readOnly: true
            -
              mountPath: /etc/helm
              name: jenkins-helm-keys
              readOnly: true
            -
              mountPath: /etc/k8s-config
              name: k8s-config
              readOnly: false
      volumes:
      - name: jenkins-ssh-keys
        secret:
          secretName: jenkins-ssh-zonar-jenkins
          defaultMode: 0400
      - name: jenkins-gke-keys
        secret:
          secretName: jenkins-gke-zonar-jenkins
      - name: jenkins-helm-keys
        secret:
          secretName: jenkins-helm-zonar-jenkins
      - name: k8s-config
        configMap:
          name: {{ template "fullname" . }}-configuration
          defaultMode: 0775
