# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# github, jenkins or ldap
adminEmail: "me@email.com"
adminPassword: "admin"
adminUser: "admin"
javaOptions: "-Xms1024m -Xmx1024m -Djenkins.install.runSetupWizard=false"
jenkinsHookUrl:
jenkinsUrl: "jenkins.somedomain.io"
jobsRepo: "URL to jobs repo"
workflowRepo: "https://github.com/samsung-cnct/k8s-pipeline-library"
seedJobToken: "seed"

# github, jenkins or ldap
security: "jenkins"
adminUserSalt: "change me if using jenkins security"

# Storageclass must be pre provisioned on the Kubernetes cluster prior to installing jenkins
persistence:
  component: "data_volume"
  storageClass: "storageclass name"
  zone: "comma seperated availibility zones for GCP"         # ie. us-east1-b, us-east1-a, us-east1-c, us-east1-f
  enabled: true
  accessMode: "ReadWriteOnce"
  claimName: "jenkins-jobs"
  size: 10Gi

slack:
  slackDomain: "samsung-cnct"
  slackRoom: "#ping-jenkins"
  slackApiToken: "change me"

github:
  githubClientId: "change me"
  githubAccessToken: "change me"
  githubUserName: "change me"
  githubOrgNames: "change me"
  githubClientKey: "change me"
  admin_usernames: "change me"

gke:
  clusterName: "production-cluster"
  clusterPrimaryZone: "us-east1-b"
  gkeProject: "change me"
  svcAccountId: "change me"
  svcAccountKey: "change me"

ssh:
  sshPrivateKey: "change me"
  sshPublicKey: "change me"

persistence:
  component: "data_volume"
  enabled: false
  storageClass: "generic"
  reclaiming: "Retained"
  accessMode: "ReadWriteOnce"
  size: 8Gi

ldap:
  ldapServer:
  rootDN:
  userSearchBase:
  userSearchFilter: "uid={0}"
  groupMembershipFilter:
  managerDN:
  managerDNPassword: "change me"

agent:
  images:
    gradle: "set me"
    gke: "set me"  
  cpu: "200m"
  memory: "1024Mi"
  port: 50000

master:
  image: "set me"
  cpu: "200m"
  memory: "1024Mi"
  port: 8080
  serviceType: "NodePort"

helm:
  svcAccountId: "change me"
  svcAccountKey: "change me"
