apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    name: jenkins
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    component: "{{.Release.Name}}-jenkins-master"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
    "kubernetes.io/loadbalancer-class": "{{ .Values.loadbalancer }}"
    {{- if .Values.master.externalPort }}
    "loadbalancer-port.lbex/masterport": "{{ .Values.master.lbexPort }}"
    {{- end }}
spec:
  ports:
    - port: {{.Values.master.port}}
      name: masterport
    - port: {{.Values.agent.port}}
      name: agentport
  selector:
    name: jenkins
  type: {{.Values.master.serviceType}}