apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    name: jenkins
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-jenkins-master"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  ports:
    - port: {{.Values.master.port}}
      name: masterport
      targetPort: {{.Values.master.port}}
      nodePort: {{.Values.master.nodePort}}
    - port: {{.Values.agent.port}}
      targetPort: {{.Values.agent.port}}
      name: agentport
  selector:
    name: jenkins
  type: {{.Values.master.serviceType}}