# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# github, jenkins or ldap
adminEmail: "maratoid+samsungjenkins@gmail.com"
adminPassword: "admin"
adminUser: "admin"
javaOptions: "-Xms512m -Xmx512m -Djenkins.install.runSetupWizard=false"
jenkinsUrl: "jenkins.cnct.io"
jobsRepo: "https://github.com/samsung-cnct/kraken-ci-jobs"
kubernetes_cluster: "production-cluster"
secretName: "cluster-secrets"
secretVolume: "/etc/gke-secrets"
gkeProject: "sds-readiness"

# github, jenkins or ldap
security: "jenkins"
adminUserSalt: "change me if using jenkins security"

slackDomain: "samsung-cnct"
slackRoom: "#ping-jenkins"

persistence:
  component: "data_volume"
  enabled: false
  storageClass: "generic"
  accessMode: "ReadWriteOnce"
  size: 8Gi

ldap:
  ldapServer:
  rootDN:
  userSearchBase:
  userSearchFilter: "uid={0}"
  groupMembershipFilter:
  managerDN:
  managerDNPassword: "change me"

github:
  admin_usernames: "zonarbot jfelten countspongebob l337ch maratoid mikeln richardkaufmann Rick-Lindberg SamsungAGJenkinsBot spiffxp davidewatson cwazy1 coffeepac venezia jooyeong alejandroEsc sostheim DStorck leahnp kmansel"

agent:
  image: "quay.io/samsung_cnct/jenkins-kubernetes-slave:latest"
  cpu: "200m"
  memory: "256Mi"
  port: 50000

master:
  image: "quay.io/samsung_cnct/jenkins-kubernetes-master:latest"
  cpu: "200m"
  memory: "512Mi"
  port: 8080

secrets:
  slackApiToken: "change me"
  githubClientId: "change me"
  githubAccessToken: "change me"
  githubUserName: "change me"
  githubClientKey: "change me"
  sshPrivateKeyFile:
  sshPrivateKey: "change me"
  sshPublicKeyFile:
  sshPublicKey: "change me"
  svcAccountId: "change me"
  svcAccountKeyFile:
  svcAccountKey: "change me"
