apiVersion: v1
kind: Secret
metadata: 
  name: cluster-secrets
  annotations:
    "helm.sh/hook": pre-install
data:
  service-account-id: {{ .Values.secrets.svcAccountId | b64enc | quote }}
{{if .Values.secrets.svcAccountKeyFile}}
  service-account.json: {{ include .Values.secrets.svcAccountKeyFile | b64enc | replace "\n" "" | quote }}
{{else}}
  service-account.json: {{ .Values.secrets.svcAccountKey | b64enc | replace "\n" "" | quote }}
{{end}}
  helm-service-account-id: {{ .Values.secrets.helmRepoSvcAccountId | b64enc | quote }}
{{if .Values.secrets.svcAccountKeyFile}}
  helm-service-account.json: {{ include .Values.secrets.helmRepoSvcAccountKeyFile | b64enc | replace "\n" "" | quote }}
{{else}}
  helm-service-account.json: {{ .Values.secrets.helmRepoSvcAccountKey | b64enc | replace "\n" "" | quote }}
{{end}}