apiVersion: v1
kind: Service
metadata:
  name: {{template "jenkins" . }}
  labels:
    name: {{template "jenkins" . }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Jenkins.Master.Component}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
    - port: {{.Values.Jenkins.Master.SlaveListenerPort}}
      targetPort: {{.Values.Jenkins.Master.SlaveListenerPort}}
      name: slavelistener
  selector:
    name: "{{template "jenkins" . }}"
  type: ClusterIP