apiVersion: batch/v1
kind: Secret
metadata:
  name: "jenkins-secrets"
  annotations:
    "helm.sh/hook": pre-install
data:
  slackapitoken: {{ .Values.secrets.slackApiToken | b64enc | quote }}
  githubclientid: {{ .Values.secrets.githubClientId | b64enc | quote }}
  githubaccesstoken: {{ .Values.secrets.githubAccessToken | b64enc | quote }}
  githubusername: {{ .Values.secrets.githubUserName | b64enc | quote }}
  githubclientkey: {{ .Values.secrets.githubClientKey | b64enc | quote }}
{{if .Values.secrets.sshPrivateKeyFile}}
  ssh-privatekey: {{ include .Values.secrets.sshPrivateKeyFile | b64enc | replace "\n" "" | quote }}
{{else}}
  ssh-privatekey: {{ .Values.secrets.sshPrivateKey | b64enc | replace "\n" "" | quote }}
{{end}}
{{if .Values.secrets.sshPublicKeyFile}}
  ssh-publickey: {{ include .Values.secrets.sshPublicKeyFile | b64enc | replace "\n" "" | quote }}
{{else}}
  ssh-publickey: {{ .Values.secrets.sshPublicKey | b64enc | replace "\n" "" | quote }}
{{end}}