apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    name: jenkins
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-jenkins-master"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  ports:
    - port: {{.Values.master.port}}
      name: masterPort
      targetPort: {{.Values.master.port}}
    - port: {{.Values.agent.port}}
      targetPort: {{.Values.agent.port}}
      name: agentPort
  selector:
    name: jenkins
  type: ClusterIP